### ISSUE TITLE
Truncated antialiasing of GL points

### ISSUE THREAD

**Issue by c42f** [JuliaPlots/GLMakie.jl#15]
I've noticed that there's some problems with point antialiasing on scatter plots. For example, in the standard example

http://makie.juliaplots.org/stable/examples-scatter.html#Tutorial-markersize-1
![tutorial_markersize jpg](https://user-images.githubusercontent.com/601473/52546882-88242200-2e0e-11e9-9346-d9e2f5209aa2.png)

the point antialiasing makes the points look square, particularly the point at `(4,4)` and the smallest one. This appears to depend on how the point sprites fit onto the grid of pixels, and changes as the plot window is scaled.

My guess is that there's an off-by-one or off-by-half pixel error somewhere which is making the antialiased output color not exactly equal to the background color at the edge of the sprite. Thus causing inconsistency depending on how the sprite overlays the grid of fragments. But it could be something else, my reading of the shader pipeline was superficial (I'm assuming this example goes via the sprite geom+vert+frag signed distance antialiasing pipeline).

**Comment by SimonDanisch** [comment]
Ok, I think I know what's going on. I'm anti-aliasing one unit left / right to the border, and since the border is directly on the quad edge, this means cutting off here and there... Need to figure out the cleanest solution, since that `one unit` isn't simple to calculate and also, best text rendering needs to be one unit left/right to look good.

**Comment by SimonDanisch** [comment]
I came up with a first solution, but I'm not too happy with it: https://github.com/JuliaPlots/GLMakie.jl/compare/sd-aashader?expand=1

**Comment by c42f** [comment]
Your solution here looks great visually. Regarding choosing a value for `ALIASING_CONST`... sampling theory probably has something to say about "ideal" spatial filter bandwidth etc being hit when `ALIASING_CONST=1.0` but from past experience I think you shouldn't worry too much about that and just choose the most visually pleasing value ;-) Personally I would err on the side of crisp and slightly aliased.

Anyway, after playing with it for a while, I do wonder whether there's a bug which makes the sampled SDFs for text twice as steep as the computed ones. The dots seem awfully blurry compared to the text.

Somewhat OT: I just came across this great font rendering demo again: http://wdobbie.com/pdf/ it's so pretty, if only it was simpler to implement!

**Comment by c42f** [comment]
> The dots seem awfully blurry compared to the text.

I might take that back, doing some more staring at pixels they look pretty similar. It could be that the relatively simpler shape of the dots just looks better with less antialiasing.

Doing a bit more reading of the shader, I notice that `aastep` computes `length(vec2(dFdx(value), dFdy(value)))` where `value` is the signed distance in uv coordinates. Which looks like it will deal automatically with any scaling of the SDF. Though that entire part of the calculation could be avoided if the SDF were scaled so that it's in pixel coordinates in which case the gradient would be one by definition. I suppose you could get the scale factor by computing `dFdx(f_uv)`, `dFdy(f_uv)` which would probably be more well behaved and robust than doing it on the SDF directly which has a more complicated form.

**Comment by c42f** [comment]
Back to the solution for this particular problem... I think we should be guided by the following principle:

* The integral of the color over space should be fixed, regardless of the value of `ALIASING_CONST`.

I think this implies that your original fragment shader code is correct, and that we should be padding the quad out in the vertex shader by `ALIASING_CONST/2` of a pixel instead.

**Comment by c42f** [comment]
> you could get the scale factor by computing dFdx(f_uv), dFdy(f_uv) which would probably be more well behaved and robust than doing it on the SDF directly which has a more complicated form

I tried this out. The text antialiasing is *much* improved by doing this!

**Comment by c42f** [comment]
> we should be padding the quad out in the geometry shader

I tried to get this working, but it requires the viewport size in the shader which is annoying. I'm not sure how to hand this through cleanly, what do you think?

**Comment by c42f** [comment]
By the way, it's wonderful to have this whole stack in pure julia. Thank you :-)

**Comment by c42f** [comment]
For some hacks I did while investigating how to fix this, see:
https://github.com/c42f/GLMakie.jl/tree/cjf/aa_dist_field

While some of those hacks are horrible hardcoded things, the 2D text antialiasing is significantly better for small text sizes on that branch.
