### ISSUE TITLE
ETA on switching to the new registrator system?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaPlots/GLMakie.jl#33]
The current GLMakie version is compatible to `ImageCore <= 0.7.4`, and it conflicts with `Images 0.18`, which requires `ImageCore >= 0.8.2`

issue: https://github.com/JuliaImages/ImageDistances.jl/issues/20

I'll make compatibility changes in `ImageDistances.jl`, in the meantime, I'd like to know the ETA of JuliaPlots switching to the new registrator. I suppose a trivial version bump can solve the problem.

@timholy Looks like we're going too quickly upgrading versions?

cc: @babaq

**Comment by SimonDanisch** [comment]
Any idea how this happened? I never put an version constraints on ImageCore..

**Comment by johnnychen94** [comment]
It's related to package resolver in the GeneralRegistry.

https://github.com/JuliaRegistries/General/blob/4307fb1ca19859bf9f9268e7f59ae5c161c96dbb/G/GLMakie/Compat.toml

My guess on its previous mechanism is:

When you registry a version, it sets default package compatibilities to `0-x.y`, where `x.y` is the latest existing version.

And looks like they've changed this behavior to `0-*` recently. https://github.com/JuliaRegistries/General/pull/549
