### ISSUE TITLE
Failing build on macOS 10.13.6

### ISSUE THREAD

**Issue by lstagner** [JuliaPlots/GLMakie.jl#5]
When I try to build GLMakie I get the following error. I manually installed the opengl library using `brew install glfw3` but it doesn't seem to be finding the library. GLFW seems to build fine. I am using `Makie#master, AbstractPlotting#master, GLMakie#master`

```julia
  Building GLFW ────────────→ `~/.julia/packages/GLFW/69NQ7/deps/build.log`
  Building GDAL ────────────→ `~/.julia/packages/GDAL/vec6Y/deps/build.log`
  Building GLMakie ─────────→ `~/.julia/packages/GLMakie/30EXr/deps/build.log`
┌ Error: Error building `GLMakie`: 
│ Your OpenGL version is too low! Update your driver or GPU! Version found: 1.68.0, version required: 3.3
│ init error of GLFW
│ ERROR: LoadError: OpenGL/GLFW wasn't installed correctly. This likely means,
│ you don't have an OpenGL capable Graphic Card,
│ you don't have the newest video driver installed,
│ or the GLFW build failed. If you're on linux and `]build` GLFW failed,
│ try manually adding `sudo apt-get install libglfw3` and then `]build GLMakie`.
│ If you're on a headless server, you still need to install x-server and
│ propper GPU drivers. You can take inspiration from this article
│ on how to get Makie running on a headless system:
│ https://nextjournal.com/sdanisch/makie-1.0
│ If you don't have a GPU, there is also a Cairo software backend
│ for Makie which you can use:
│ https://github.com/JuliaPlots/CairoMakie.jl.
│ Please check the below error and open an issue at:
│ https://github.com/JuliaPlots/GLMakie.jl.
│ After you fixed your OpenGL install, please run `]build GLMakie` again!
│ GLMakie will still load, but will be disabled as a default backend for Makie
```

**Comment by wsrinin** [comment]
I have the same problem as well.

**Comment by wsrinin** [comment]
The version of my open GL is actually 4.1 but somehow GLMakie shows that it is not.

**Comment by wsrinin** [comment]
I actually dig deeper into the issue. I don't think the problem lies with GLFW.jl since I can create the window just fine and I have no trouble building it as well. When I try to build ModernGL there seem to be some problems associated with it. I don't know whether this is actually the root of the problem above or not.

**Comment by wsrinin** [comment]
May be this is the problem

` m = match(r"(\d+)\.(\d+)\.(\d+)?(.*)", glversion)
    # I don't really trust that all vendors have a version that matches
    # the above regex, so let's make no match non fatal! `

**Comment by SimonDanisch** [comment]
Yeah indeed - so much for trying to give better errors...sorry about this, apple does things always completely different -.- 
Can you tell me what this gives you:
```Julia
using ModernGL
    # Create a windowed mode window and its OpenGL context
    window = GLFW.CreateWindow(10, 10, "OpenGL Example")
    # Make the window's context current
    GLFW.HideWindow(window)
    GLFW.MakeContextCurrent(window)
glversion = unsafe_string(glGetString(GL_VERSION))
```

**Comment by SimonDanisch** [comment]
or if you want to be absolutely amazing, just make a PR with the correct regex for osx :)

**Comment by lstagner** [comment]
When I run it I get `"2.1 ATI-1.68.20"` for the version string and `RegexMatch("1.68.20", 1="1", 2="68", 3="20", 4="")` for the Regex

**Comment by wsrinin** [comment]
I don't know how to make a PR but I think this is the correct regex for OSX

`m = match(r"(\d+)\.(\d+)\s", glversion)`

This will give me 4.1.0 as a version of my OpenGL, which is correct.

**Comment by wsrinin** [comment]
I will change the code base on my machine to this and report later whether this works or not,

**Comment by wsrinin** [comment]
Now I ran into a completely different. Somehow yesterday I got the `glversion` to be 4.1. Today when I create the window and check the context of my version again I got 2.1, a very different number. :(

**Comment by SimonDanisch** [comment]
Ah, I'm probably not setting the window hints right to get the highest version - which seems to be fine on most platforms but macos :P

**Comment by SimonDanisch** [comment]
can you try: https://github.com/JuliaPlots/GLMakie.jl/pull/7

**Comment by SimonDanisch** [comment]
oooh, so you didn't keep it backwards compatible!? :D 
can you just show me what the actual string is, so we can find a regex matching all?

**Comment by wsrinin** [comment]
Is this what you want to see? I am not quite sure what you mean by keeping backward compatible.

<img width="1029" alt="screen shot 2018-12-08 at 2 47 09 pm" src="https://user-images.githubusercontent.com/24701859/49690047-7796b900-faf8-11e8-83af-c2ef72edf486.png">

**Comment by SimonDanisch** [comment]
ah, so we just need the 3rd one to be optional...

**Comment by lstagner** [comment]
The branch works for me as well. Thanks for your hard work.
