### ISSUE TITLE
possible bug in `color_lookup`

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/GLMakie.jl#81]
https://github.com/JuliaPlots/GLMakie.jl/blob/76b57fad1a1a0674977ccf5b095bdaafa56be635/src/GLVisualize/utils.jl#L145-L151

If I understand correctly, it seems that

`mix_linearly(cmap[i_a], cmap[i_b], scaled)`

should be

`mix_linearly(cmap[i_a], cmap[i_b], index-i_a)`

**Comment by SimonDanisch** [comment]
Thanks! I wonder if that function is even still used anywhere :D

**Comment by SimonDanisch** [comment]
I removed this function in https://github.com/JuliaPlots/GLMakie.jl/pull/76
